### ISSUE TITLE
Fatal error on Moodle 4.3+

### ISSUE THREAD

**Issue by krmu** [srobotta/moodle-tiny_cloze#17] opened 2023-12-10 12:13 UTC
On Moode 4.3+ (Build: 20231116) we have error that looks like:

![image](https://github.com/srobotta/moodle-tiny_cloze/assets/53869559/29b47941-d892-4206-9617-31b95b2f231c)

And console says:
![image](https://github.com/srobotta/moodle-tiny_cloze/assets/53869559/5367d2dd-4422-4ba8-94b1-aec38f0f56b8)

And in final, we are not able to use Cloze editor at all.

**Comment by marcusgreen** [comment] 2023-12-10 21:29
What theme are you using?

**Comment by krmu** [comment] 2023-12-10 21:31
> What theme are you using?

Boost

**Comment by srobotta** [comment] 2023-12-11 10:55
Hi,

Apart from the warning that the modal_factory has been deprecated since Moodle 4.3. the plugin works for me. Could you please switch of the Javascript cache in the administration settings, then run it again? The console error should not appear in first.js but in the actual file.
Please post output here again.

Thank you.
Best regards, Stephan

**Comment by krmu** [comment] 2023-12-11 11:39
> Hi,
> 
> Apart from the warning that the modal_factory has been deprecated since Moodle 4.3. the plugin works for me. Could you please switch of the Javascript cache in the administration settings, then run it again? The console error should not appear in first.js but in the actual file. Please post output here again.
> 
> Thank you. Best regards, Stephan

Tried to clear out all caches, disabled Javascript cache, but wont work for me.

![image](https://github.com/srobotta/moodle-tiny_cloze/assets/53869559/33cd4c3b-e92b-475f-8243-3d414ccfa05a)

![image](https://github.com/srobotta/moodle-tiny_cloze/assets/53869559/1aa18f1f-e851-4403-9394-de90df0e9d66)

**Comment by srobotta** [comment] 2023-12-13 17:24
Hi,

in the current main branch, I have changed the code to use the new Modal.create function that exists since 4.3. For older Moodle versions, the ModalFactory is still in use. That should make the deprecation warning disappear in the console.

However, I think your problem might still persist because I have tested with 4.3 and the current dev branch and have no issues with the plugin. If you can, try to disable other (first tinyMCE but maybe others) plugins to see if the error has something to do with your setup. At the moment I have no clue how to help you any further, without being able to reproduce the problem here.

BTW: which browser are you using?

Best regards, Stephan

**Comment by krmu** [comment] 2023-12-14 09:51
> Hi,
> 
> in the current main branch, I have changed the code to use the new Modal.create function that exists since 4.3. For older Moodle versions, the ModalFactory is still in use. That should make the deprecation warning disappear in the console.
> 
> However, I think your problem might still persist because I have tested with 4.3 and the current dev branch and have no issues with the plugin. If you can, try to disable other (first tinyMCE but maybe others) plugins to see if the error has something to do with your setup. At the moment I have no clue how to help you any further, without being able to reproduce the problem here.
> 
> BTW: which browser are you using?
> 
> Best regards, Stephan

Hey. I'm using Brave browser.

**Comment by srobotta** [comment] 2023-12-14 10:56
Hi,

I have just tested the Brave Browser with the current Moodle dev branch and the main branch of the cloze question plugin as well on an installation of Moodle 4.3 and the cloze editor plugin in version 1.1. At both installations I still don't see any error.
I suggest to continue debugging your installation. I am afraid, there might be some interference with another plugin, even up to the point that the culprit is not the cloze question plugin.

Best regards, Stephan

**Comment by marcusgreen** [comment] 2023-12-15 12:14
@krmu  Would it be possible to have an account on your site to test out this functionality, I guess it would need to be a teacher account on an otherwise unused course.

**Comment by krmu** [comment] 2024-01-03 21:02
> @krmu Would it be possible to have an account on your site to test out this functionality, I guess it would need to be a teacher account on an otherwise unused course.

Hey, sorry for very late answer. 

Our Moodle is isolated, it's not possible.

**Comment by srobotta** [comment] 2024-04-25 07:37
I am closing this because it seems to be an issue only on @krmu your specific installation.

**Closed by srobotta** 2024-04-25 07:37 UTC

**Comment by krmu** [comment] 2024-04-29 06:41
Hello! 

Today update Moodle to version 4.4 and also Tiny Cloze to latest version.
Now everything works!

Thanks!
